### ISSUE TITLE
CephFS Stroage Class needs fsName field

### ISSUE THREAD

**Issue by figassis** [darxkies/k8s-tew#27]
Otherwise you get a missing field fsName when provisioning. Correct definition is:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: storage
  name: csi-cephfs
provisioner: cephfs.csi.ceph.com
reclaimPolicy: Delete
parameters:
  clusterID: clusterid
  fsName: cephfs
  pool: cephfs
  mounter: kernel
  provisionVolume: "true"
  csi.storage.k8s.io/provisioner-secret-name: csi-cephfs-secret
  csi.storage.k8s.io/provisioner-secret-namespace: storage
  csi.storage.k8s.io/controller-expand-secret-name: csi-cephfs-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: storage
  csi.storage.k8s.io/node-stage-secret-name: csi-cephfs-secret
  csi.storage.k8s.io/node-stage-secret-namespace: storage
  allowVolumeExpansion: "true"
```
